name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${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}
        run: |
          git config --global user.email "haridas498689@example.com"
          git config --global user.name "Haridas498689"
          
          git remote add hf "https://Haridas498689:$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@huggingface.co/spaces/Haridas498689/joshai_123"
          
          git push --force hf main
